version: "3.7"

services:
#  redis:
#    restart: always
#    build:
#      context: ./docker/redis
#      dockerfile: Dockerfile
#    ports:
#      - "6379:6379"
  db:
# Постоянная перезагрузка контейнера. Даже в случае остановки или рестарта ОС
    restart: always
    privileged: true
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db
    ports:
      # Бд доступна на порту 5432, можно и для других приложений использовать
      - "5432:5432"
    # Решение проблемы когда бэкенд запускается раньше чем БД
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d todos -U radif" ]
      interval: 3s
      timeout: 3s
      retries: 9
    networks:
      - my_network
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HOME: /home/app
        APP_HOME: /home/app/backend
        STATIC_FILES: /home/app/backend/staticfiles
        MEDIA_FILES: /home/app/backend/mediafiles
    volumes:
      - static:/home/app/backend/static
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
    depends_on:
      - db
    # Доступен для внутренней сети, но недоступен для наружней
    expose:
      - 3333
    env_file:
      - ./.env.dev
    networks:
      - my_network
  nginx:
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
# Бэкенд доступен на порту 222 и 333. Для доступа добавить к ip или домену
# Но в главном контейнере, где стоит основной Nginx сервис раздаётся на
# https://backend.radif.ru
      - "222:80"
      - "333:443"
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
# Подключаю сертификаты, которые получил в центре сертификации - Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - my_network
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
# Фронтенд доступен на порту 22222 и 33333. Для доступа добавить к ip или домену
# Но в главном контейнере, где стоит основной Nginx сервис раздаётся на
# https://frontend.radif.ru
      - "22222:80"
      - "33333:443"
    depends_on:
      - nginx
    volumes:
      - frontend_volume:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./frontend.nginx.cond:/etc/nginx/nginx.conf
    networks:
      - my_network

volumes:
  postgres_data:
  static:
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
  frontend_volume:

networks:
  my_network:
# Драйвер сети
    driver: bridge
# Имя сети
    name: my_network
# Подключение к внешней сети. Если её нет - необходимо создать!
    external: true
